// Seed data used the first time the database is initialized.
// After that, everything lives in Postgres and is edited from /admin.

const CORE_AI_ENGINEERING = [
  "Python & Programming",
  "الرياضيات للذكاء الاصطناعي",
  "معالجة البيانات",
  "تعلم الآلة",
  "التعلم العميق",
];

const DEFAULT_PATHS = [
  {
    id: "data-analyst",
    emoji: "📊",
    titleAr: "محلل بيانات",
    titleEn: "Data Analyst",
    accent: "#3FBF9F",
    accentSoft: "rgba(63,191,159,0.16)",
    tagline: "يحوّل البيانات إلى رؤى تساعد الشركات على اتخاذ قرارات مبنية على الحقائق.",
    def: "محلل البيانات يجمع البيانات وينظفها ويحللها ويعرض نتائجها باستخدام أدوات مثل Excel وSQL وPython وPower BI.",
    why: "يساعد الشركات على فهم الأداء وتحسين المبيعات وتقليل التكاليف واتخاذ قرارات دقيقة.",
    opportunities: "يُعد من أكثر الوظائف طلبًا في مختلف القطاعات مثل الأعمال، التسويق، البنوك، الصحة والتجارة الإلكترونية، مع استمرار نمو الطلب عالميًا.",
    core: null,
    roadmap: [
      { title: "Python Basics", tags: ["Variables", "Data Types", "Conditions", "Loops", "Functions", "Files"] , sources: [] },
      { title: "Excel Basics", tags: ["SUM / AVERAGE / MAX / MIN / IF", "VLOOKUP", "XLOOKUP", "Pivot Tables", "Charts"] , sources: [] },
      { title: "Statistics Fundamentals", tags: ["Mean", "Median", "Mode", "Variance", "Std. Deviation", "Probability", "Correlation", "Hypothesis Testing"] , sources: [] },
      { title: "Data Cleaning & Preparation", tags: ["Missing Values", "Duplicates", "Data Types", "Outliers", "Pandas", "NumPy"] , sources: [] },
      { title: "Python for Data Analysis", tags: ["Pandas", "NumPy", "Matplotlib", "Seaborn"] , sources: [] },
      { title: "Excel for Data Analysis", tags: ["Pivot Tables", "Advanced Formulas", "Dashboards", "Reports"] , sources: [] },
      { title: "SQL Fundamentals", tags: ["SELECT", "WHERE", "GROUP BY", "JOIN", "INSERT / UPDATE / DELETE"] , sources: [] },
      { title: "Advanced SQL for Analytics", tags: ["CTE", "Subqueries", "Window Functions", "Data Cleaning"] , sources: [] },
      { title: "Data Visualization & BI", tags: ["Power BI", "Tableau", "Dashboards", "DAX Basics", "Data Modeling"] , sources: [] },
      { title: "Business Fundamentals", tags: ["KPIs", "Business Metrics", "Sales Analysis", "Customer Analysis", "Decision Making"] , sources: [] },
      { title: "AI Automation for Analysts", tags: ["ChatGPT for Analysis", "Automated Reports", "AI-assisted SQL", "Workflow Automation"] , sources: [] },
      { title: "Portfolio Projects", tags: ["Sales Dashboard", "Customer Analysis", "Marketing Analytics", "Financial Reports"] , sources: [] },
    ],
  },
  {
    id: "data-engineer",
    emoji: "🏗️",
    titleAr: "مهندس بيانات",
    titleEn: "Data Engineer",
    accent: "#3E7FD1",
    accentSoft: "rgba(62,127,209,0.16)",
    tagline: "يبني البنية التحتية التي تجعل البيانات جاهزة للتحليل والذكاء الاصطناعي.",
    def: "مهندس البيانات يصمم قواعد البيانات، ويبني خطوط نقل ومعالجة البيانات (ETL/ELT)، ويضمن جودة البيانات وأدائها.",
    why: "بدون مهندس البيانات لا تستطيع المؤسسات الاستفادة من بياناتها أو تشغيل أنظمة التحليل والذكاء الاصطناعي بكفاءة.",
    opportunities: "يُعتبر من أكثر تخصصات البيانات نموًا، مع طلب مرتفع في الشركات التقنية، البنوك، المؤسسات الكبرى، وخدمات الحوسبة السحابية.",
    core: null,
    roadmap: [
      { title: "Programming Basics", tags: ["Python Basics", "OOP", "Functions", "Files", "Error Handling"] , sources: [] },
      { title: "SQL Fundamentals", tags: ["SELECT", "WHERE", "JOIN", "GROUP BY", "CRUD"] , sources: [] },
      { title: "Advanced SQL", tags: ["CTE", "Subqueries", "Window Functions", "Query Optimization", "Data Cleaning"] , sources: [] },
      { title: "Database Fundamentals", tags: ["Relational Databases", "Indexing", "Normalization", "Transactions"] , sources: [] },
      { title: "Data Modeling", tags: ["ERD", "Star Schema", "Snowflake Schema", "Fact & Dimension Tables"] , sources: [] },
      { title: "ETL / ELT Concepts", tags: ["Extract", "Transform", "Load", "Data Pipelines", "Data Quality"] , sources: [] },
      { title: "Data Processing", tags: ["Pandas", "NumPy", "PySpark Basics"] , sources: [] },
      { title: "Big Data Technologies", tags: ["Apache Spark", "Hadoop Basics", "Distributed Processing"] , sources: [] },
      { title: "Data Warehousing", tags: ["Warehouse Architecture", "OLAP", "Lakehouse Concepts"] , sources: [] },
      { title: "Workflow Orchestration", tags: ["Apache Airflow", "Scheduling", "Monitoring"] , sources: [] },
      { title: "Cloud Data Engineering", tags: ["AWS", "Azure", "GCP", "Storage", "Data Services"] , sources: [] },
      { title: "Engineering Tools", tags: ["Git", "Linux", "Docker", "APIs"] , sources: [] },
      { title: "Portfolio Projects", tags: ["ETL Pipeline", "Data Warehouse", "Real-Time Pipeline"] , sources: [] },
    ],
  },
  {
    id: "analytics-engineer",
    emoji: "🧭",
    titleAr: "مهندس تحليلات",
    titleEn: "Analytics Engineer",
    accent: "#7C6AD6",
    accentSoft: "rgba(124,106,214,0.16)",
    tagline: "يربط بين هندسة البيانات وتحليل الأعمال لتحويل البيانات إلى معلومات جاهزة لاتخاذ القرار.",
    def: "يبني نماذج البيانات وينظمها باستخدام أدوات مثل dbt وSQL لتكون سهلة التحليل والاستخدام.",
    why: "يسرّع عملية إعداد التقارير ولوحات المعلومات ويضمن توحيد البيانات داخل المؤسسة.",
    opportunities: "يُعد من الوظائف الحديثة سريعة النمو، ويزداد الطلب عليه في الشركات التي تعتمد على البيانات لاتخاذ القرارات.",
    core: null,
    roadmap: [
      { title: "Programming Basics", tags: ["Python Basics", "Git"], duration: "٣ أسابيع" , sources: [] },
      { title: "SQL Mastery ⭐", tags: ["SQL Basics", "Joins", "Aggregations", "CTE", "Window Functions"], duration: "٨ أسابيع" , sources: [] },
      { title: "Database Fundamentals", tags: ["Relational Databases", "Indexing", "Transactions"], duration: "٣ أسابيع" , sources: [] },
      { title: "Data Cleaning & Transformation", tags: ["Pandas", "SQL Transformation", "Data Quality"], duration: "٤ أسابيع" , sources: [] },
      { title: "Data Modeling ⭐", tags: ["ERD", "Star Schema", "Snowflake Schema", "Fact & Dimension Tables"], duration: "٣ أسابيع" , sources: [] },
      { title: "ETL / ELT Pipelines", tags: ["Extract", "Transform", "Load", "Data Workflow"], duration: "٤ أسابيع" , sources: [] },
      { title: "Data Warehouse", tags: ["OLAP", "Warehouse Architecture", "BigQuery / Snowflake"], duration: "٣ أسابيع" , sources: [] },
      { title: "dbt (Analytics Engineering Core)", tags: ["Models", "Tests", "Documentation", "Deployment"], duration: "٤ أسابيع" , sources: [] },
      { title: "Business Analytics", tags: ["KPIs", "Metrics", "Business Logic"], duration: "٢ أسابيع" , sources: [] },
      { title: "Visualization", tags: ["Power BI", "Tableau", "Dashboards"], duration: "٤ أسابيع" , sources: [] },
      { title: "Advanced Data Engineering (اختياري)", tags: ["Spark", "Airflow", "Cloud", "Kafka"], duration: "٨ أسابيع" , sources: [] },
      { title: "Projects", tags: ["Data Warehouse", "Dashboard", "Analytics Pipeline"], duration: "٤ أسابيع" , sources: [] },
    ],
  },
  {
    id: "ml-engineer",
    emoji: "🤖",
    titleAr: "مهندس تعلم آلة",
    titleEn: "Machine Learning Engineer",
    accent: "#D6902A",
    accentSoft: "rgba(214,144,42,0.16)",
    tagline: "يطوّر نماذج تعلم الآلة التي تتعلم من البيانات وتقدم تنبؤات وقرارات ذكية.",
    def: "يبني ويُدرّب وينشر نماذج التعلم الآلي باستخدام Python وأطر مثل Scikit-learn وPyTorch وTensorFlow.",
    why: "يساعد المؤسسات على أتمتة العمليات، وتحسين التنبؤ، وتقديم حلول ذكية في مختلف المجالات.",
    opportunities: "يُعد من أكثر وظائف الذكاء الاصطناعي طلبًا، مع فرص واسعة في التقنية، الصحة، التمويل، التجارة الإلكترونية والصناعة.",
    core: null,
    roadmap: [
      { title: "Programming Basics", tags: ["Python Basics", "OOP", "Functions", "Files", "Error Handling", "Git"] , sources: [] },
      { title: "Mathematics for ML", tags: ["Linear Algebra", "Probability", "Statistics", "Basic Calculus"] , sources: [] },
      { title: "Data Processing & Analysis", tags: ["NumPy", "Pandas", "Data Cleaning", "Data Visualization", "Feature Engineering"] , sources: [] },
      { title: "SQL & Databases", tags: ["SQL Basics", "Joins", "Aggregations", "Database Fundamentals"] , sources: [] },
      { title: "Machine Learning Fundamentals ⭐", tags: ["Supervised Learning", "Unsupervised Learning", "Regression", "Classification", "Clustering", "Model Evaluation", "Overfitting"] , sources: [] },
      { title: "Advanced Machine Learning", tags: ["Feature Selection", "Hyperparameter Tuning", "Cross Validation", "Random Forest", "XGBoost", "LightGBM"] , sources: [] },
      { title: "Deep Learning Basics", tags: ["Neural Networks", "Backpropagation", "CNN", "RNN", "LSTM", "Transformers Basics", "PyTorch / TensorFlow"] , sources: [] },
      { title: "Model Deployment", tags: ["FastAPI", "REST APIs"] , sources: [] },
      { title: "MLOps Engineering ⭐", tags: ["Docker", "MLflow", "CI/CD", "Model Versioning", "Monitoring"] , sources: [] },
      { title: "Cloud & Production Systems", tags: ["AWS", "Azure"] , sources: [] },
      { title: "Portfolio Projects", tags: ["Predictive Models", "Recommendation System", "Fraud Detection", "Forecasting"] , sources: [] },
    ],
  },
  {
    id: "ai-engineer",
    emoji: "🧠",
    titleAr: "مهندس ذكاء اصطناعي",
    titleEn: "AI Engineer",
    accent: "#D65C4C",
    accentSoft: "rgba(214,92,76,0.16)",
    tagline: "يطوّر تطبيقات ذكاء اصطناعي متكاملة تعتمد على النماذج الحديثة وLLMs.",
    def: "يصمم ويبني حلولًا تعتمد على التعلم الآلي، والتعلم العميق، والنماذج اللغوية، وRAG، وAI Agents.",
    why: "يقود التحول نحو الأنظمة الذكية التي تزيد الإنتاجية وتوفر تجارب أكثر تطورًا للمستخدمين.",
    opportunities: "يُعتبر من أسرع التخصصات نموًا عالميًا، مع طلب مرتفع في الشركات الناشئة والكبرى التي تتبنى تقنيات الذكاء الاصطناعي.",
    core: null,
    roadmap: [
      { title: "Programming Foundations", tags: ["Python Basics", "OOP", "Data Structures", "APIs", "Git", "Linux Basics"] , sources: [] },
      { title: "Mathematics for AI", tags: ["Linear Algebra", "Probability", "Statistics", "Basic Calculus"] , sources: [] },
      { title: "Data Processing", tags: ["NumPy", "Pandas", "Data Cleaning", "Data Visualization", "Feature Engineering"] , sources: [] },
      { title: "Machine Learning Fundamentals ⭐", tags: ["Supervised/Unsupervised", "Regression", "Classification", "Clustering", "Scikit-learn"] , sources: [] },
      { title: "Deep Learning ⭐", tags: ["Neural Networks", "CNN", "RNN", "LSTM", "Attention", "Transformers Basics", "PyTorch / TensorFlow"] , sources: [] },
      { title: "NLP Fundamentals", tags: ["Text Processing", "Tokenization", "Embeddings", "NER", "Sentiment Analysis", "Hugging Face", "spaCy"] , sources: [] },
      { title: "Generative AI & LLMs ⭐", tags: ["GPT / Llama / Mistral", "Prompt Engineering", "Context Window", "Fine-tuning Basics", "Model APIs"] , sources: [] },
      { title: "RAG Systems ⭐", tags: ["Embeddings", "Vector Databases", "Chunking", "Retrieval", "Re-ranking", "FAISS", "LangChain / LlamaIndex"] , sources: [] },
      { title: "AI Agents ⭐", tags: ["Tool Calling", "Function Calling", "Memory", "Multi-Agent Systems", "LangGraph", "CrewAI"] , sources: [] },
      { title: "Backend & Deployment", tags: ["FastAPI", "REST APIs", "Model Serving", "Authentication"] , sources: [] },
      { title: "MLOps & Production", tags: ["Docker", "MLflow", "CI/CD", "Model Monitoring", "Cloud Basics"] , sources: [] },
      { title: "Portfolio Projects", tags: ["AI Assistant", "RAG Chatbot", "AI Agent", "Computer Vision App", "NLP Application"] , sources: [] },
    ],
  },
  {
    id: "computer-vision",
    emoji: "👁️",
    titleAr: "أخصائي رؤية حاسوبية",
    titleEn: "Computer Vision Specialist",
    accent: "#1E9FC7",
    accentSoft: "rgba(30,159,199,0.16)",
    tagline: "يطوّر أنظمة تمكّن الحاسوب من فهم الصور والفيديوهات وتحليلها.",
    def: "يبني حلولًا لمعالجة الصور واكتشاف الكائنات والتعرف على الوجوه وOCR باستخدام OpenCV وYOLO وPyTorch.",
    why: "يدخل في السيارات ذاتية القيادة، والأنظمة الأمنية، والطب، والصناعة، والروبوتات.",
    opportunities: "يشهد نموًا مستمرًا مع توسع استخدام الرؤية الحاسوبية في القطاعات الصناعية والطبية والتقنية.",
    core: CORE_AI_ENGINEERING,
    roadmap: [
      { title: "Computer Vision Fundamentals", tags: ["Images", "Pixels", "Color Spaces", "Image Processing"] , sources: [] },
      { title: "OpenCV", tags: ["Filtering", "Edge Detection", "Transformations", "Feature Extraction"] , sources: [] },
      { title: "CNN & Vision Models", tags: ["CNN Architectures", "Transfer Learning", "Fine-tuning"] , sources: [] },
      { title: "Image Classification", tags: ["Data Augmentation", "Metrics", "Pretrained Models"] , sources: [] },
      { title: "Object Detection", tags: ["YOLO", "Faster R-CNN", "SSD", "IoU", "mAP"] , sources: [] },
      { title: "Image Segmentation", tags: ["Semantic", "Instance Segmentation", "U-Net", "Mask R-CNN"] , sources: [] },
      { title: "Advanced Vision", tags: ["OCR", "Face Recognition", "Tracking", "Pose Estimation", "Vision Transformers"] , sources: [] },
      { title: "Vision Generative AI", tags: ["Diffusion Models", "Vision-Language Models"] , sources: [] },
      { title: "Deployment", tags: ["FastAPI", "Docker", "ONNX", "Edge AI"] , sources: [] },
      { title: "Projects", tags: ["Face Detection System", "OCR Document Scanner"] , sources: [] },
    ],
  },
  {
    id: "nlp-specialist",
    emoji: "💬",
    titleAr: "أخصائي معالجة لغة",
    titleEn: "NLP Specialist",
    accent: "#C13E7C",
    accentSoft: "rgba(193,62,124,0.16)",
    tagline: "يطوّر أنظمة تفهم اللغة البشرية وتتعامل مع النصوص والكلام بذكاء.",
    def: "يبني تطبيقات مثل الشات بوت، وتحليل المشاعر، والترجمة، والتلخيص، والبحث الذكي باستخدام Transformers وLLMs.",
    why: "يشكل الأساس لمعظم تطبيقات الذكاء الاصطناعي اللغوية الحديثة مثل ChatGPT والمساعدات الذكية.",
    opportunities: "يُعد من أكثر تخصصات الذكاء الاصطناعي نموًا، مع طلب متزايد في الشركات التقنية، وخدمات العملاء، والتعليم، والرعاية الصحية.",
    core: CORE_AI_ENGINEERING,
    roadmap: [
      { title: "NLP Fundamentals", tags: ["Text Processing", "Tokenization", "Normalization", "Stemming", "Lemmatization"] , sources: [] },
      { title: "Text Representation", tags: ["TF-IDF", "Word Embeddings", "Sentence Embeddings"] , sources: [] },
      { title: "NLP Tasks", tags: ["Text Classification", "NER", "Sentiment Analysis", "Similarity", "Summarization"] , sources: [] },
      { title: "Language Models", tags: ["BERT", "RoBERTa", "T5", "Hugging Face"] , sources: [] },
      { title: "Modern NLP & Transformers", tags: ["Attention", "Transformer Architecture", "Fine-tuning"] , sources: [] },
      { title: "Generative NLP & LLMs", tags: ["LLMs", "GPT", "Llama", "Prompt Engineering", "Context Window"] , sources: [] },
      { title: "RAG Systems ⭐", tags: ["Embeddings", "Vector Databases", "Chunking", "Retrieval", "Re-ranking"] , sources: [] },
      { title: "AI Agents ⭐", tags: ["Tool Calling", "Function Calling", "Memory", "Planning", "LangChain / LangGraph"] , sources: [] },
      { title: "AI Applications", tags: ["Chatbots", "Document AI", "Question Answering", "Enterprise AI Assistants"] , sources: [] },
      { title: "Deployment", tags: ["FastAPI", "Docker", "Model Serving"] , sources: [] },
      { title: "Projects", tags: ["Sentiment Analysis", "Resume Analyzer"] , sources: [] },
    ],
  },
];

module.exports = { DEFAULT_PATHS, CORE_AI_ENGINEERING };
